#########################################
#Config File to Load all Global Variables
#########################################

#Variable needed for Watson
watson:
  username: 'c70ffd84-8509-4e5b-947e-78bbd3516547'
  password: 'Sn0vju3OBYG5'
  classifier_ids:
    model1_v1_old: '0015c6x266-nlc-33059'
    model2_v1_old: '0015b6x265-nlc-29393'
    models1: '57a445x277-nlc-362'
    models2: '556e1ex274-nlc-537'
    modeld1: '558839x276-nlc-499'
    modeld2: '558839x276-nlc-501'
    model1: '558839x276-nlc-125'
    model2: '557d2fx275-nlc-127'
    model_categorize: '718eedx290-nlc-456'
  confidence_requirements:
    overall: 0.7
    model1: 0.7
    model2: 0.7
#Variables needed for exchange
exchange:
  username: 'corp\chris'
  smtp: 'chris@corp.contoso.com'
  password: 'ABC123xyz!'
  server: 'nyclawexchdev.eastus.cloudapp.azure.com'
  email_groups:
    email_group_1:
      eastern_district: 'ecf_bounces@nyed.uscourts.gov'
      southern_district: 'nysd_ecf_pool@nysd.uscourts.gov'
    email_group_2:
      supreme_court: 'efile@nycourts.gov'
#Variables to set directories for any output files
models:
  training:
    model1_file: '/users/drichards/Desktop/NYCLaw/TrainingData-M1-py.txt'
    model2_file: '/users/drichards/Desktop/NYCLaw/TrainingData-M2-py.txt'
    modeld1_file: '/users/drichards/Desktop/NYCLaw/TrainingData-MD1-py.txt'
    modeld2_file: '/users/drichards/Desktop/NYCLaw/TrainingData-MD2-py.txt'
    models1_file: '/users/drichards/Desktop/NYCLaw/TrainingData-MS1-py.txt'
    models2_file: '/users/drichards/Desktop/NYCLaw/TrainingData-MS2-py.txt'
    category_file: '/users/drichards/Desktop/NYCLaw/TrainingCategories.txt'
    training_folder: 'Training'
    training_subfolder_1: 'actionable'
    training_subfolder_2: 'nonactionable'
  analysis:
    output_file: '/users/drichards/Desktop/NYCLaw/ResultAnalysis_4Models.txt'
disclaimers:
  disclaimer1: 'This is an automatic e-mail message generated by the CM/ECF system. Please DO NOT RESPOND to this e-mail because the mail box is unattended. ***NOTE TO PUBLIC ACCESS USERS*** Judicial Conference of the United States policy permits attorneys of record and parties in a case (including pro se litigants) to receive one free electronic copy of all documents filed electronically if receipt is required by law or directed by the filer. PACER access fees apply to all other users. To avoid later charges download a copy of each document during this first viewing. However if the referenced document is a transcript the free copy and 30 page limit do not apply.  '
  disclaimer2: '[https://iapps.courts.state.ny.us/nyscef/images/NYSCEF/jasper_state_seal.gif] '
